### ISSUE TITLE
Standard formula interface

### ISSUE THREAD

**Issue by grantmcdermott** [kylebutts/jive#1]
Hey, this looks very promising. A wrote a JIVE vcov thing for myself a while ago, but yours looks much more comprehensive.

One suggestion is to use a standard formula (user-level) interface. I would follow fixest's lead in specifying that the final slot is always IV (to allow a middle FE slot too). Internal parsing should be pretty easy using Formula.

So your README example would become:

```r
jive(
  guilt ~ i(black) + i(white) | bailDate | jail3 ~ judge_pre,
  data = stephenson
)
```

**Comment by grantmcdermott** [comment]
Oops, I just saw further below in the README that you're already considering a formula interface. Still... I might be missing something, but why not use a three-part formula (as I have above) instead of a four-part formula?

**Comment by kylebutts** [comment]
@grantmcdermott  The initial reason was this is what you would have to do for high-dimensional FEs as an instrument:
```r
guilt ~ i(black) + i(white) | bailDate | jail3 ~ i(judge_pre)
```
Instead of this
```r
guilt ~ i(black) + i(white) | bailDate | jail3 ~ 0 | judge_pre
```
If I wanted to efficiently estimate it (using proper FE estimation for `judge_pre`), I would have to convert the `i` to fixed effects and it would get complicated. But, I think I figured out a way to parse the formula, so I'll likely switch over. 

I prefer the latter because JIVE supports continuous covariates as instruments, so it's good to support this.

**Comment by kylebutts** [comment]
Completed in da77164
